### ISSUE TITLE
install on an asus merlin router?

### ISSUE THREAD

**Issue by netconstructor** [layeh/google-apps-radius#6]
I am not sure if you are familiar with the open source firmware called "Asus Merlin" but its essentially an excellent firmware replacement for nearly all Asus routers (similar to TomatoUSB/DDWRT). See: https://github.com/RMerl/asuswrt-merlin

My question was simply to see if you might be able to provide some insight on how one might be able to integrate you auth approach to integrate with the existing freeradius2 solution outlined here:
https://github.com/RMerl/asuswrt-merlin/wiki/Setting-up-FreeRadius2-through-Entware

If this is not easily possible would it be feasible to implement your approach through Optware/Entware (both of which are compatible with the asus merlin firmware: see: https://github.com/RMerl/asuswrt-merlin/wiki)

Any thoughts on how best this might be accomplished?

**Comment by ghost** [comment]
> Any thoughts on how best this might be accomplished?

I don't, sorry.
