### ISSUE TITLE
Unable to login if 2FA is enabled on the google account

### ISSUE THREAD

**Issue by ssbarnea** [layeh/google-apps-radius#7]
It seems that the README file does not include any information regarding usage when 2FA is enabled on Google.

**Comment by ghost** [comment]
since we auth via smtp, you will probably have to generate an app password or whatever they're called.

**Comment by ssbarnea** [comment]
Thank you! I used https://security.google.com/settings/security/apppasswords to generate an app password, named it "radius" in order to remember where it should work and tested it. It worked.

While this is not ideal, it still works.
